module.exports = [
  {
    deviceGroupId: 1,
    deviceGroupName: "BATT",
    deviceGroupDescription: "Battery",
    statusId: 2,
    statusName: "FAULTED",
    devices: [
      {
        deviceId: 69,
        deviceName: "BATT1",
        desc: null,
        deviceNum: null,
        firmwareVersion: null,
        serialNo: null,
        uniqueIdentifier: "qa-1-batt-1-new2133",
        buildNo: null,
        siteId: 2,
        deviceStatusId: 2,
        deviceGroupId: 1,
        gridStatus: null,
        make: null,
        deviceType: {
          deviceTypeId: null,
          deviceTypeName: "ESS-R1",
          deviceGroupName: "BATT",
          deviceGroupDescription: "Battery",
        },
        deviceModel: null,
        points: [
          {
            name: "Data_Connection",
            type: "string",
            label: "Data Connection Type",
            desc: "DataConnType",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "0",
            _static: 0,
            size: null,
            detail: "Data Connection Type",
            symbols: [
              {
                name: "Landline",
                value: 1,
                label: null,
                desc: null,
              },
              {
                name: "Cellular",
                value: 2,
                label: null,
                desc: null,
              },
              {
                name: "Disconnected",
                value: 3,
                label: null,
                desc: null,
              },
            ],
            comments: null,
            value: "3",
            maxValueRange: null,
            minValueRange: null,
            tag: "Data_Connection",
          },
          {
            name: "Unique_ID",
            type: "string",
            label: "Unique ID",
            desc: "Unique ID",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Unique ID",
            symbols: [],
            comments: null,
            value: "qa-1-batt-1-new2133",
            maxValueRange: null,
            minValueRange: null,
            tag: "Unique_ID",
          },
          {
            name: "Dev_Status",
            type: "uint16",
            label: "Dev_Status",
            desc: "Dev_Status",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Device Status",
            symbols: [],
            comments: null,
            value: "2",
            maxValueRange: null,
            minValueRange: null,
            tag: "Dev_Status",
          },
        ],
      },
      {
        deviceId: 72,
        deviceName: "BATT2",
        desc: null,
        deviceNum: null,
        firmwareVersion: null,
        serialNo: null,
        uniqueIdentifier: "new-device-daniel",
        buildNo: null,
        siteId: 2,
        deviceStatusId: 2,
        deviceGroupId: 1,
        gridStatus: null,
        make: null,
        deviceType: {
          deviceTypeId: null,
          deviceTypeName: "ESS-R1",
          deviceGroupName: "BATT",
          deviceGroupDescription: "Battery",
        },
        deviceModel: null,
        points: [
          {
            name: "Model",
            type: "string",
            label: "Model",
            desc: "Model",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "0",
            _static: 0,
            size: null,
            detail: null,
            symbols: [],
            comments: null,
            value: "The Model of the Battery 2",
            maxValueRange: null,
            minValueRange: null,
            tag: "Model",
          },
          {
            name: "Rating",
            type: "string",
            label: "Energy Rating",
            desc: "Energy Rating",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "0",
            _static: 0,
            size: null,
            detail: "Energy Rating",
            symbols: [],
            comments: null,
            value: "333",
            maxValueRange: null,
            minValueRange: null,
            tag: "Rating",
          },
          {
            name: "Make",
            type: "string",
            label: "Make",
            desc: "Make",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "0",
            _static: 1,
            size: null,
            detail: null,
            symbols: [],
            comments: null,
            value: "Make",
            maxValueRange: null,
            minValueRange: null,
            tag: "Make",
          },
          {
            name: "LCM_Loc",
            type: "string",
            label: "LCM_Loc",
            desc: "LCM_Loc",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "0",
            _static: 1,
            size: null,
            detail: null,
            symbols: [],
            comments: null,
            value: "1",
            maxValueRange: null,
            minValueRange: null,
            tag: "LCM_Loc",
          },
          {
            name: "LCM_Rac_Num",
            type: "string",
            label: "LCM_Rac_Num",
            desc: "LCM_Rac_Num",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "0",
            _static: 1,
            size: null,
            detail: null,
            symbols: [],
            comments: null,
            value: "2",
            maxValueRange: null,
            minValueRange: null,
            tag: "LCM_Rac_Num",
          },
          {
            name: "LCM_Pos_Num",
            type: "string",
            label: "LCM_Pos_Num",
            desc: "LCM_Pos_Num",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "0",
            _static: 1,
            size: null,
            detail: null,
            symbols: [],
            comments: null,
            value: "3",
            maxValueRange: null,
            minValueRange: null,
            tag: "LCM_Pos_Num",
          },
          {
            name: "Inverter_On_grid",
            type: "string",
            label: "Inverter_On_grid",
            desc: "Inverter_On_grid",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "0",
            _static: 1,
            size: null,
            detail: null,
            symbols: [],
            comments: null,
            value: true,
            maxValueRange: null,
            minValueRange: null,
            tag: "Inverter_On_grid",
          },
        ],
      },
      {
        deviceId: 75,
        deviceName: "BATT3",
        desc: null,
        deviceNum: null,
        firmwareVersion: null,
        serialNo: "6666666",
        uniqueIdentifier: "battery-from-udt-test-34343",
        buildNo: "3453453",
        siteId: 2,
        deviceStatusId: null,
        deviceGroupId: 1,
        gridStatus: null,
        make: null,
        deviceType: {
          deviceTypeId: null,
          deviceTypeName: "ESS-R1",
          deviceGroupName: "BATT",
          deviceGroupDescription: "Battery",
        },
        deviceModel: null,
        points: [
          {
            name: "Make",
            type: "string",
            label: "Make",
            desc: "Make",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "0",
            _static: 1,
            size: null,
            detail: null,
            symbols: [],
            comments: null,
            value: "Make",
            maxValueRange: null,
            minValueRange: null,
            tag: "Make",
          },
          {
            name: "Model",
            type: "string",
            label: "Model",
            desc: "Model",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "0",
            _static: 0,
            size: null,
            detail: null,
            symbols: [],
            comments: null,
            value: "The Model",
            maxValueRange: null,
            minValueRange: null,
            tag: "Model",
          },
          {
            name: "Serial_Num",
            type: "string",
            label: "Serial #",
            desc: "Serial #",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 1,
            size: null,
            detail: "Serial #",
            symbols: [],
            comments: null,
            value: "6666666",
            maxValueRange: null,
            minValueRange: null,
            tag: "Serial_Num",
          },
          {
            name: "Firm_Ver",
            type: "string",
            label: "Firmware Version",
            desc: "Firmware Version",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "0",
            _static: 0,
            size: null,
            detail: "Firmware Version",
            symbols: [],
            comments: null,
            value: "343433",
            maxValueRange: null,
            minValueRange: null,
            tag: "Firm_Ver",
          },
          {
            name: "Unique_ID",
            type: "string",
            label: "Unique ID",
            desc: "Unique ID",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "0",
            _static: 1,
            size: null,
            detail: "Unique ID",
            symbols: [],
            comments: null,
            value: "battery-from-udt-test-34343",
            maxValueRange: null,
            minValueRange: null,
            tag: "Unique_ID",
          },
          {
            name: "Build_Num",
            type: "string",
            label: "Build #",
            desc: "NoBuild",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "0",
            _static: 0,
            size: null,
            detail: "Build Number",
            symbols: [],
            comments: null,
            value: "3453453",
            maxValueRange: null,
            minValueRange: null,
            tag: "Build_Num",
          },
          {
            name: "Rating",
            type: "string",
            label: "Energy Rating",
            desc: "Energy Rating",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "0",
            _static: 0,
            size: null,
            detail: "Energy Rating",
            symbols: [],
            comments: null,
            value: "333",
            maxValueRange: null,
            minValueRange: null,
            tag: "Rating",
          },
          {
            name: "Description",
            type: "string",
            label: "Device description",
            desc: "Device description",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "0",
            _static: 0,
            size: null,
            detail: "Device description",
            symbols: [],
            comments: null,
            value: "4",
            maxValueRange: null,
            minValueRange: null,
            tag: "Description",
          },
        ],
      },
      {
        deviceId: 76,
        deviceName: "BATT4",
        desc: null,
        deviceNum: null,
        firmwareVersion: null,
        serialNo: "12345678900",
        uniqueIdentifier: "new-device-8888585",
        buildNo: "343",
        siteId: 2,
        deviceStatusId: 2,
        deviceGroupId: 1,
        gridStatus: null,
        make: null,
        deviceType: {
          deviceTypeId: null,
          deviceTypeName: "ESS-R1",
          deviceGroupName: "BATT",
          deviceGroupDescription: "Battery",
        },
        deviceModel: null,
        points: [
          {
            name: "Unique_ID",
            type: "string",
            label: "Unique ID",
            desc: "Unique ID",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Unique ID",
            symbols: [],
            comments: null,
            value: "new-device-8888585",
            maxValueRange: null,
            minValueRange: null,
            tag: "Unique_ID",
          },
          {
            name: "Dev_Status",
            type: "uint16",
            label: "Dev_Status",
            desc: "Dev_Status",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Device Status",
            symbols: [],
            comments: null,
            value: "2",
            maxValueRange: null,
            minValueRange: null,
            tag: "Dev_Status",
          },
        ],
      },
    ],
  },
  {
    deviceGroupId: 3,
    deviceGroupName: "WIND",
    deviceGroupDescription: "WIND",
    statusId: 4,
    statusName: "WARNING",
    devices: [
      {
        deviceId: 92,
        deviceName: "WIND1",
        desc: null,
        deviceNum: null,
        firmwareVersion: null,
        serialNo: "6666666",
        uniqueIdentifier: "WIND1-device-sds385",
        buildNo: null,
        siteId: 2,
        deviceStatusId: null,
        deviceGroupId: 3,
        gridStatus: null,
        make: null,
        deviceType: {
          deviceTypeId: null,
          deviceTypeName: "WIND-R1",
          deviceGroupName: "WIND",
          deviceGroupDescription: "WIND",
        },
        deviceModel: null,
        points: [
          {
            name: "Make",
            type: "string",
            label: "Make",
            desc: "Make",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Make",
            symbols: [],
            comments: null,
            value: "1232dfdf",
            maxValueRange: null,
            minValueRange: null,
            tag: "Make",
          },
          {
            name: "Model",
            type: "string",
            label: "Model",
            desc: "Model",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Model",
            symbols: [],
            comments: null,
            value: "New Model sds",
            maxValueRange: null,
            minValueRange: null,
            tag: "Model",
          },
          {
            name: "Serial_Num",
            type: "string",
            label: "Serial #",
            desc: "Serial #",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Serial #",
            symbols: [],
            comments: null,
            value: "6666666",
            maxValueRange: null,
            minValueRange: null,
            tag: "Serial_Num",
          },
          {
            name: "Unique_ID",
            type: "string",
            label: "Unique ID",
            desc: "Unique ID",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Unique ID",
            symbols: [],
            comments: null,
            value: "WIND1-device-sds385",
            maxValueRange: null,
            minValueRange: null,
            tag: "Unique_ID",
          },
        ],
      },
    ],
  },
  {
    deviceGroupId: 4,
    deviceGroupName: "RENGINE",
    deviceGroupDescription: "RENGINE",
    statusId: 5,
    statusName: "OK",
    devices: [
      {
        deviceId: 102,
        deviceName: "RENGINE2",
        desc: null,
        deviceNum: null,
        firmwareVersion: null,
        serialNo: "6666666",
        uniqueIdentifier: "RENGINE2-device-sds385",
        buildNo: null,
        siteId: 2,
        deviceStatusId: null,
        deviceGroupId: 4,
        gridStatus: null,
        make: null,
        deviceType: {
          deviceTypeId: null,
          deviceTypeName: "RENGINE-R1",
          deviceGroupName: "RENGINE",
          deviceGroupDescription: "RENGINE",
        },
        deviceModel: null,
        points: [
          {
            name: "Make",
            type: "string",
            label: "Make",
            desc: "Make",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Make",
            symbols: [],
            comments: null,
            value: "1232dfdf",
            maxValueRange: null,
            minValueRange: null,
            tag: "Make",
          },
          {
            name: "Model",
            type: "string",
            label: "Model",
            desc: "Model",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Model",
            symbols: [],
            comments: null,
            value: "New Model sds",
            maxValueRange: null,
            minValueRange: null,
            tag: "Model",
          },
          {
            name: "Serial_Num",
            type: "string",
            label: "Serial #",
            desc: "Serial #",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Serial #",
            symbols: [],
            comments: null,
            value: "6666666",
            maxValueRange: null,
            minValueRange: null,
            tag: "Serial_Num",
          },
          {
            name: "Unique_ID",
            type: "string",
            label: "Unique ID",
            desc: "Unique ID",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Unique ID",
            symbols: [],
            comments: null,
            value: "RENGINE2-device-sds385",
            maxValueRange: null,
            minValueRange: null,
            tag: "Unique_ID",
          },
        ],
      },
      {
        deviceId: 103,
        deviceName: "RENGINE1",
        desc: null,
        deviceNum: null,
        firmwareVersion: null,
        serialNo: "6666666",
        uniqueIdentifier: "RENGINE1-device-sds385",
        buildNo: null,
        siteId: 2,
        deviceStatusId: null,
        deviceGroupId: 4,
        gridStatus: null,
        make: null,
        deviceType: {
          deviceTypeId: null,
          deviceTypeName: "RENGINE-R1",
          deviceGroupName: "RENGINE",
          deviceGroupDescription: "RENGINE",
        },
        deviceModel: null,
        points: [
          {
            name: "Make",
            type: "string",
            label: "Make",
            desc: "Make",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Make",
            symbols: [],
            comments: null,
            value: "1232dfdf",
            maxValueRange: null,
            minValueRange: null,
            tag: "Make",
          },
          {
            name: "Model",
            type: "string",
            label: "Model",
            desc: "Model",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Model",
            symbols: [],
            comments: null,
            value: "New Model sds",
            maxValueRange: null,
            minValueRange: null,
            tag: "Model",
          },
          {
            name: "Serial_Num",
            type: "string",
            label: "Serial #",
            desc: "Serial #",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Serial #",
            symbols: [],
            comments: null,
            value: "6666666",
            maxValueRange: null,
            minValueRange: null,
            tag: "Serial_Num",
          },
          {
            name: "Unique_ID",
            type: "string",
            label: "Unique ID",
            desc: "Unique ID",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Unique ID",
            symbols: [],
            comments: null,
            value: "RENGINE1-device-sds385",
            maxValueRange: null,
            minValueRange: null,
            tag: "Unique_ID",
          },
        ],
      },
    ],
  },
  {
    deviceGroupId: 5,
    deviceGroupName: "DCLOAD",
    deviceGroupDescription: "DCLOAD",
    statusId: 4,
    statusName: "WARNING",
    devices: [
      {
        deviceId: 100,
        deviceName: "DCLOAD2",
        desc: null,
        deviceNum: null,
        firmwareVersion: null,
        serialNo: "6666666",
        uniqueIdentifier: "DCLOAD2-device-sds385",
        buildNo: null,
        siteId: 2,
        deviceStatusId: null,
        deviceGroupId: 5,
        gridStatus: null,
        make: null,
        deviceType: {
          deviceTypeId: null,
          deviceTypeName: "DCLOAD-R1",
          deviceGroupName: "DCLOAD",
          deviceGroupDescription: "DCLOAD",
        },
        deviceModel: null,
        points: [
          {
            name: "Make",
            type: "string",
            label: "Make",
            desc: "Make",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Make",
            symbols: [],
            comments: null,
            value: "1232dfdf",
            maxValueRange: null,
            minValueRange: null,
            tag: "Make",
          },
          {
            name: "Model",
            type: "string",
            label: "Model",
            desc: "Model",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Model",
            symbols: [],
            comments: null,
            value: "New Model sds",
            maxValueRange: null,
            minValueRange: null,
            tag: "Model",
          },
          {
            name: "Serial_Num",
            type: "string",
            label: "Serial #",
            desc: "Serial #",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Serial #",
            symbols: [],
            comments: null,
            value: "6666666",
            maxValueRange: null,
            minValueRange: null,
            tag: "Serial_Num",
          },
          {
            name: "Unique_ID",
            type: "string",
            label: "Unique ID",
            desc: "Unique ID",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Unique ID",
            symbols: [],
            comments: null,
            value: "DCLOAD2-device-sds385",
            maxValueRange: null,
            minValueRange: null,
            tag: "Unique_ID",
          },
        ],
      },
      {
        deviceId: 101,
        deviceName: "DCLOAD1",
        desc: null,
        deviceNum: null,
        firmwareVersion: null,
        serialNo: "6666666",
        uniqueIdentifier: "DCLOAD-device-sds385",
        buildNo: null,
        siteId: 2,
        deviceStatusId: null,
        deviceGroupId: 5,
        gridStatus: null,
        make: null,
        deviceType: {
          deviceTypeId: null,
          deviceTypeName: "DCLOAD-R1",
          deviceGroupName: "DCLOAD",
          deviceGroupDescription: "DCLOAD",
        },
        deviceModel: null,
        points: [
          {
            name: "Make",
            type: "string",
            label: "Make",
            desc: "Make",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Make",
            symbols: [],
            comments: null,
            value: "1232dfdf",
            maxValueRange: null,
            minValueRange: null,
            tag: "Make",
          },
          {
            name: "Model",
            type: "string",
            label: "Model",
            desc: "Model",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Model",
            symbols: [],
            comments: null,
            value: "New Model sds",
            maxValueRange: null,
            minValueRange: null,
            tag: "Model",
          },
          {
            name: "Serial_Num",
            type: "string",
            label: "Serial #",
            desc: "Serial #",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Serial #",
            symbols: [],
            comments: null,
            value: "6666666",
            maxValueRange: null,
            minValueRange: null,
            tag: "Serial_Num",
          },
          {
            name: "Unique_ID",
            type: "string",
            label: "Unique ID",
            desc: "Unique ID",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Unique ID",
            symbols: [],
            comments: null,
            value: "DCLOAD-device-sds385",
            maxValueRange: null,
            minValueRange: null,
            tag: "Unique_ID",
          },
        ],
      },
    ],
  },
  {
    deviceGroupId: 6,
    deviceGroupName: "ACLOAD",
    deviceGroupDescription: "ACLOAD",
    statusId: 3,
    statusName: "ALARM",
    devices: [
      {
        deviceId: 96,
        deviceName: "ACLOAD2",
        desc: null,
        deviceNum: null,
        firmwareVersion: null,
        serialNo: "6666666",
        uniqueIdentifier: "ACLOAD2-device-sds385",
        buildNo: null,
        siteId: 2,
        deviceStatusId: null,
        deviceGroupId: 6,
        gridStatus: null,
        make: null,
        deviceType: {
          deviceTypeId: null,
          deviceTypeName: "ACLOAD-R1",
          deviceGroupName: "ACLOAD",
          deviceGroupDescription: "ACLOAD",
        },
        deviceModel: null,
        points: [
          {
            name: "Make",
            type: "string",
            label: "Make",
            desc: "Make",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Make",
            symbols: [],
            comments: null,
            value: "1232dfdf",
            maxValueRange: null,
            minValueRange: null,
            tag: "Make",
          },
          {
            name: "Model",
            type: "string",
            label: "Model",
            desc: "Model",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Model",
            symbols: [],
            comments: null,
            value: "New Model sds",
            maxValueRange: null,
            minValueRange: null,
            tag: "Model",
          },
          {
            name: "Serial_Num",
            type: "string",
            label: "Serial #",
            desc: "Serial #",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Serial #",
            symbols: [],
            comments: null,
            value: "6666666",
            maxValueRange: null,
            minValueRange: null,
            tag: "Serial_Num",
          },
          {
            name: "Unique_ID",
            type: "string",
            label: "Unique ID",
            desc: "Unique ID",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Unique ID",
            symbols: [],
            comments: null,
            value: "ACLOAD2-device-sds385",
            maxValueRange: null,
            minValueRange: null,
            tag: "Unique_ID",
          },
        ],
      },
      {
        deviceId: 97,
        deviceName: "ACLOAD1",
        desc: null,
        deviceNum: null,
        firmwareVersion: null,
        serialNo: "6666666",
        uniqueIdentifier: "ACLOAD-device-sds385",
        buildNo: null,
        siteId: 2,
        deviceStatusId: null,
        deviceGroupId: 6,
        gridStatus: null,
        make: null,
        deviceType: {
          deviceTypeId: null,
          deviceTypeName: "ACLOAD-R1",
          deviceGroupName: "ACLOAD",
          deviceGroupDescription: "ACLOAD",
        },
        deviceModel: null,
        points: [
          {
            name: "Make",
            type: "string",
            label: "Make",
            desc: "Make",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Make",
            symbols: [],
            comments: null,
            value: "1232dfdf",
            maxValueRange: null,
            minValueRange: null,
            tag: "Make",
          },
          {
            name: "Model",
            type: "string",
            label: "Model",
            desc: "Model",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Model",
            symbols: [],
            comments: null,
            value: "New Model sds",
            maxValueRange: null,
            minValueRange: null,
            tag: "Model",
          },
          {
            name: "Serial_Num",
            type: "string",
            label: "Serial #",
            desc: "Serial #",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Serial #",
            symbols: [],
            comments: null,
            value: "6666666",
            maxValueRange: null,
            minValueRange: null,
            tag: "Serial_Num",
          },
          {
            name: "Unique_ID",
            type: "string",
            label: "Unique ID",
            desc: "Unique ID",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Unique ID",
            symbols: [],
            comments: null,
            value: "ACLOAD-device-sds385",
            maxValueRange: null,
            minValueRange: null,
            tag: "Unique_ID",
          },
        ],
      },
      {
        deviceId: 98,
        deviceName: "ACLOAD3",
        desc: null,
        deviceNum: null,
        firmwareVersion: null,
        serialNo: "6666666",
        uniqueIdentifier: "ACLOAD3-device-sds385",
        buildNo: null,
        siteId: 2,
        deviceStatusId: null,
        deviceGroupId: 6,
        gridStatus: null,
        make: null,
        deviceType: {
          deviceTypeId: null,
          deviceTypeName: "ACLOAD-R1",
          deviceGroupName: "ACLOAD",
          deviceGroupDescription: "ACLOAD",
        },
        deviceModel: null,
        points: [
          {
            name: "Make",
            type: "string",
            label: "Make",
            desc: "Make",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Make",
            symbols: [],
            comments: null,
            value: "1232dfdf",
            maxValueRange: null,
            minValueRange: null,
            tag: "Make",
          },
          {
            name: "Model",
            type: "string",
            label: "Model",
            desc: "Model",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Model",
            symbols: [],
            comments: null,
            value: "New Model sds",
            maxValueRange: null,
            minValueRange: null,
            tag: "Model",
          },
          {
            name: "Serial_Num",
            type: "string",
            label: "Serial #",
            desc: "Serial #",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Serial #",
            symbols: [],
            comments: null,
            value: "6666666",
            maxValueRange: null,
            minValueRange: null,
            tag: "Serial_Num",
          },
          {
            name: "Unique_ID",
            type: "string",
            label: "Unique ID",
            desc: "Unique ID",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Unique ID",
            symbols: [],
            comments: null,
            value: "ACLOAD3-device-sds385",
            maxValueRange: null,
            minValueRange: null,
            tag: "Unique_ID",
          },
        ],
      },
      {
        deviceId: 99,
        deviceName: "ACLOAD4",
        desc: null,
        deviceNum: null,
        firmwareVersion: null,
        serialNo: "6666666",
        uniqueIdentifier: "ACLOAD4-device-sds385",
        buildNo: null,
        siteId: 2,
        deviceStatusId: null,
        deviceGroupId: 6,
        gridStatus: null,
        make: null,
        deviceType: {
          deviceTypeId: null,
          deviceTypeName: "ACLOAD-R1",
          deviceGroupName: "ACLOAD",
          deviceGroupDescription: "ACLOAD",
        },
        deviceModel: null,
        points: [
          {
            name: "Make",
            type: "string",
            label: "Make",
            desc: "Make",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Make",
            symbols: [],
            comments: null,
            value: "1232dfdf",
            maxValueRange: null,
            minValueRange: null,
            tag: "Make",
          },
          {
            name: "Model",
            type: "string",
            label: "Model",
            desc: "Model",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Model",
            symbols: [],
            comments: null,
            value: "New Model sds",
            maxValueRange: null,
            minValueRange: null,
            tag: "Model",
          },
          {
            name: "Serial_Num",
            type: "string",
            label: "Serial #",
            desc: "Serial #",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Serial #",
            symbols: [],
            comments: null,
            value: "6666666",
            maxValueRange: null,
            minValueRange: null,
            tag: "Serial_Num",
          },
          {
            name: "Unique_ID",
            type: "string",
            label: "Unique ID",
            desc: "Unique ID",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Unique ID",
            symbols: [],
            comments: null,
            value: "ACLOAD4-device-sds385",
            maxValueRange: null,
            minValueRange: null,
            tag: "Unique_ID",
          },
        ],
      },
    ],
  },
  {
    deviceGroupId: 7,
    deviceGroupName: "EV",
    deviceGroupDescription: "EV",
    statusId: 1,
    statusName: "MAINTENANCE",
    devices: [
      {
        deviceId: 93,
        deviceName: "EV3",
        desc: null,
        deviceNum: null,
        firmwareVersion: null,
        serialNo: "6666666",
        uniqueIdentifier: "EV3-device-sds385",
        buildNo: null,
        siteId: 2,
        deviceStatusId: null,
        deviceGroupId: 7,
        gridStatus: null,
        make: null,
        deviceType: {
          deviceTypeId: null,
          deviceTypeName: "EV-R1",
          deviceGroupName: "EV",
          deviceGroupDescription: "EV",
        },
        deviceModel: null,
        points: [
          {
            name: "Make",
            type: "string",
            label: "Make",
            desc: "Make",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Make",
            symbols: [],
            comments: null,
            value: "1232dfdf",
            maxValueRange: null,
            minValueRange: null,
            tag: "Make",
          },
          {
            name: "Model",
            type: "string",
            label: "Model",
            desc: "Model",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Model",
            symbols: [],
            comments: null,
            value: "New Model sds",
            maxValueRange: null,
            minValueRange: null,
            tag: "Model",
          },
          {
            name: "Serial_Num",
            type: "string",
            label: "Serial #",
            desc: "Serial #",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Serial #",
            symbols: [],
            comments: null,
            value: "6666666",
            maxValueRange: null,
            minValueRange: null,
            tag: "Serial_Num",
          },
          {
            name: "Unique_ID",
            type: "string",
            label: "Unique ID",
            desc: "Unique ID",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Unique ID",
            symbols: [],
            comments: null,
            value: "EV3-device-sds385",
            maxValueRange: null,
            minValueRange: null,
            tag: "Unique_ID",
          },
        ],
      },
      {
        deviceId: 94,
        deviceName: "EV1",
        desc: null,
        deviceNum: null,
        firmwareVersion: null,
        serialNo: "6666666",
        uniqueIdentifier: "EV1-device-sds385",
        buildNo: null,
        siteId: 2,
        deviceStatusId: null,
        deviceGroupId: 7,
        gridStatus: null,
        make: null,
        deviceType: {
          deviceTypeId: null,
          deviceTypeName: "EV-R1",
          deviceGroupName: "EV",
          deviceGroupDescription: "EV",
        },
        deviceModel: null,
        points: [
          {
            name: "Make",
            type: "string",
            label: "Make",
            desc: "Make",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Make",
            symbols: [],
            comments: null,
            value: "1232dfdf",
            maxValueRange: null,
            minValueRange: null,
            tag: "Make",
          },
          {
            name: "Model",
            type: "string",
            label: "Model",
            desc: "Model",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Model",
            symbols: [],
            comments: null,
            value: "New Model sds",
            maxValueRange: null,
            minValueRange: null,
            tag: "Model",
          },
          {
            name: "Serial_Num",
            type: "string",
            label: "Serial #",
            desc: "Serial #",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Serial #",
            symbols: [],
            comments: null,
            value: "6666666",
            maxValueRange: null,
            minValueRange: null,
            tag: "Serial_Num",
          },
          {
            name: "Unique_ID",
            type: "string",
            label: "Unique ID",
            desc: "Unique ID",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Unique ID",
            symbols: [],
            comments: null,
            value: "EV1-device-sds385",
            maxValueRange: null,
            minValueRange: null,
            tag: "Unique_ID",
          },
        ],
      },
      {
        deviceId: 95,
        deviceName: "EV2",
        desc: null,
        deviceNum: null,
        firmwareVersion: null,
        serialNo: "6666666",
        uniqueIdentifier: "EV2-device-sds385",
        buildNo: null,
        siteId: 2,
        deviceStatusId: null,
        deviceGroupId: 7,
        gridStatus: null,
        make: null,
        deviceType: {
          deviceTypeId: null,
          deviceTypeName: "EV-R1",
          deviceGroupName: "EV",
          deviceGroupDescription: "EV",
        },
        deviceModel: null,
        points: [
          {
            name: "Make",
            type: "string",
            label: "Make",
            desc: "Make",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Make",
            symbols: [],
            comments: null,
            value: "1232dfdf",
            maxValueRange: null,
            minValueRange: null,
            tag: "Make",
          },
          {
            name: "Model",
            type: "string",
            label: "Model",
            desc: "Model",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Model",
            symbols: [],
            comments: null,
            value: "New Model sds",
            maxValueRange: null,
            minValueRange: null,
            tag: "Model",
          },
          {
            name: "Serial_Num",
            type: "string",
            label: "Serial #",
            desc: "Serial #",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Serial #",
            symbols: [],
            comments: null,
            value: "6666666",
            maxValueRange: null,
            minValueRange: null,
            tag: "Serial_Num",
          },
          {
            name: "Unique_ID",
            type: "string",
            label: "Unique ID",
            desc: "Unique ID",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Unique ID",
            symbols: [],
            comments: null,
            value: "EV2-device-sds385",
            maxValueRange: null,
            minValueRange: null,
            tag: "Unique_ID",
          },
        ],
      },
    ],
  },
  {
    deviceGroupId: 9,
    deviceGroupName: "CDEMAND",
    deviceGroupDescription: "CDEMAND",
    statusId: 2,
    statusName: "FAULTED",
    devices: [
      {
        deviceId: 77,
        deviceName: "CDEMAND1",
        desc: null,
        deviceNum: null,
        firmwareVersion: null,
        serialNo: null,
        uniqueIdentifier: "new-cdemand-device-ss8585",
        buildNo: null,
        siteId: 2,
        deviceStatusId: 3,
        deviceGroupId: 9,
        gridStatus: null,
        make: null,
        deviceType: {
          deviceTypeId: null,
          deviceTypeName: "CDEMAND-R1",
          deviceGroupName: "CDEMAND",
          deviceGroupDescription: "CDEMAND",
        },
        deviceModel: null,
        points: [
          {
            name: "Unique_ID",
            type: "string",
            label: "Unique ID",
            desc: "Unique ID",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Unique ID",
            symbols: [],
            comments: null,
            value: "new-cdemand-device-ss8585",
            maxValueRange: null,
            minValueRange: null,
            tag: "Unique_ID",
          },
          {
            name: "Dev_Status",
            type: "uint16",
            label: "Dev_Status",
            desc: "Dev_Status",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Device Status",
            symbols: [],
            comments: null,
            value: "3",
            maxValueRange: null,
            minValueRange: null,
            tag: "Dev_Status",
          },
        ],
      },
      {
        deviceId: 80,
        deviceName: "CDEMAND2",
        desc: null,
        deviceNum: null,
        firmwareVersion: null,
        serialNo: null,
        uniqueIdentifier: "new-cdemand-device-sds385",
        buildNo: null,
        siteId: 2,
        deviceStatusId: null,
        deviceGroupId: 9,
        gridStatus: null,
        make: null,
        deviceType: {
          deviceTypeId: null,
          deviceTypeName: "CDEMAND-R1",
          deviceGroupName: "CDEMAND",
          deviceGroupDescription: "CDEMAND",
        },
        deviceModel: null,
        points: [
          {
            name: "Make",
            type: "string",
            label: "Make",
            desc: "Make",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Make",
            symbols: [],
            comments: null,
            value: "1232dfdf",
            maxValueRange: null,
            minValueRange: null,
            tag: "Make",
          },
          {
            name: "Model",
            type: "string",
            label: "Model",
            desc: "Model",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Model",
            symbols: [],
            comments: null,
            value: "New Model sds",
            maxValueRange: null,
            minValueRange: null,
            tag: "Model",
          },
          {
            name: "Unique_ID",
            type: "string",
            label: "Unique ID",
            desc: "Unique ID",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Unique ID",
            symbols: [],
            comments: null,
            value: "new-cdemand-device-sds385",
            maxValueRange: null,
            minValueRange: null,
            tag: "Unique_ID",
          },
        ],
      },
      {
        deviceId: 81,
        deviceName: "CDEMAND3",
        desc: null,
        deviceNum: null,
        firmwareVersion: null,
        serialNo: null,
        uniqueIdentifier: "new-cdemand3-device-sds385",
        buildNo: null,
        siteId: 2,
        deviceStatusId: null,
        deviceGroupId: 9,
        gridStatus: null,
        make: null,
        deviceType: {
          deviceTypeId: null,
          deviceTypeName: "CDEMAND-R1",
          deviceGroupName: "CDEMAND",
          deviceGroupDescription: "CDEMAND",
        },
        deviceModel: null,
        points: [
          {
            name: "Make",
            type: "string",
            label: "Make",
            desc: "Make",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Make",
            symbols: [],
            comments: null,
            value: "1232dfdf",
            maxValueRange: null,
            minValueRange: null,
            tag: "Make",
          },
          {
            name: "Model",
            type: "string",
            label: "Model",
            desc: "Model",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Model",
            symbols: [],
            comments: null,
            value: "New Model sds",
            maxValueRange: null,
            minValueRange: null,
            tag: "Model",
          },
          {
            name: "Unique_ID",
            type: "string",
            label: "Unique ID",
            desc: "Unique ID",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Unique ID",
            symbols: [],
            comments: null,
            value: "new-cdemand3-device-sds385",
            maxValueRange: null,
            minValueRange: null,
            tag: "Unique_ID",
          },
        ],
      },
      {
        deviceId: 82,
        deviceName: "CDEMAND4",
        desc: null,
        deviceNum: null,
        firmwareVersion: null,
        serialNo: null,
        uniqueIdentifier: "new-cdemand4-device-sds385",
        buildNo: null,
        siteId: 2,
        deviceStatusId: null,
        deviceGroupId: 9,
        gridStatus: null,
        make: null,
        deviceType: {
          deviceTypeId: null,
          deviceTypeName: "CDEMAND-R1",
          deviceGroupName: "CDEMAND",
          deviceGroupDescription: "CDEMAND",
        },
        deviceModel: null,
        points: [
          {
            name: "Make",
            type: "string",
            label: "Make",
            desc: "Make",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Make",
            symbols: [],
            comments: null,
            value: "1232dfdf",
            maxValueRange: null,
            minValueRange: null,
            tag: "Make",
          },
          {
            name: "Model",
            type: "string",
            label: "Model",
            desc: "Model",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Model",
            symbols: [],
            comments: null,
            value: "New Model sds",
            maxValueRange: null,
            minValueRange: null,
            tag: "Model",
          },
          {
            name: "Unique_ID",
            type: "string",
            label: "Unique ID",
            desc: "Unique ID",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Unique ID",
            symbols: [],
            comments: null,
            value: "new-cdemand4-device-sds385",
            maxValueRange: null,
            minValueRange: null,
            tag: "Unique_ID",
          },
        ],
      },
      {
        deviceId: 84,
        deviceName: "CDEMAND5",
        desc: null,
        deviceNum: null,
        firmwareVersion: null,
        serialNo: null,
        uniqueIdentifier: "new-cdemand5-device-sds385",
        buildNo: null,
        siteId: 2,
        deviceStatusId: null,
        deviceGroupId: 9,
        gridStatus: null,
        make: null,
        deviceType: {
          deviceTypeId: null,
          deviceTypeName: "CDEMAND-R1",
          deviceGroupName: "CDEMAND",
          deviceGroupDescription: "CDEMAND",
        },
        deviceModel: null,
        points: [
          {
            name: "Make",
            type: "string",
            label: "Make",
            desc: "Make",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Make",
            symbols: [],
            comments: null,
            value: "1232dfdf",
            maxValueRange: null,
            minValueRange: null,
            tag: "Make",
          },
          {
            name: "Model",
            type: "string",
            label: "Model",
            desc: "Model",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Model",
            symbols: [],
            comments: null,
            value: "New Model sds",
            maxValueRange: null,
            minValueRange: null,
            tag: "Model",
          },
          {
            name: "Unique_ID",
            type: "string",
            label: "Unique ID",
            desc: "Unique ID",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Unique ID",
            symbols: [],
            comments: null,
            value: "new-cdemand5-device-sds385",
            maxValueRange: null,
            minValueRange: null,
            tag: "Unique_ID",
          },
        ],
      },
      {
        deviceId: 85,
        deviceName: "CDEMAND6",
        desc: null,
        deviceNum: null,
        firmwareVersion: null,
        serialNo: null,
        uniqueIdentifier: "new-cdemand6-device-sds385",
        buildNo: null,
        siteId: 2,
        deviceStatusId: null,
        deviceGroupId: 9,
        gridStatus: null,
        make: null,
        deviceType: {
          deviceTypeId: null,
          deviceTypeName: "CDEMAND-R1",
          deviceGroupName: "CDEMAND",
          deviceGroupDescription: "CDEMAND",
        },
        deviceModel: null,
        points: [
          {
            name: "Make",
            type: "string",
            label: "Make",
            desc: "Make",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Make",
            symbols: [],
            comments: null,
            value: "1232dfdf",
            maxValueRange: null,
            minValueRange: null,
            tag: "Make",
          },
          {
            name: "Model",
            type: "string",
            label: "Model",
            desc: "Model",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Model",
            symbols: [],
            comments: null,
            value: "New Model sds",
            maxValueRange: null,
            minValueRange: null,
            tag: "Model",
          },
          {
            name: "Unique_ID",
            type: "string",
            label: "Unique ID",
            desc: "Unique ID",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Unique ID",
            symbols: [],
            comments: null,
            value: "new-cdemand6-device-sds385",
            maxValueRange: null,
            minValueRange: null,
            tag: "Unique_ID",
          },
        ],
      },
      {
        deviceId: 86,
        deviceName: "CDEMAND7",
        desc: null,
        deviceNum: null,
        firmwareVersion: null,
        serialNo: null,
        uniqueIdentifier: "new-cdemand7-device-sds385",
        buildNo: null,
        siteId: 2,
        deviceStatusId: null,
        deviceGroupId: 9,
        gridStatus: null,
        make: null,
        deviceType: {
          deviceTypeId: null,
          deviceTypeName: "CDEMAND-R1",
          deviceGroupName: "CDEMAND",
          deviceGroupDescription: "CDEMAND",
        },
        deviceModel: null,
        points: [
          {
            name: "Make",
            type: "string",
            label: "Make",
            desc: "Make",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Make",
            symbols: [],
            comments: null,
            value: "1232dfdf",
            maxValueRange: null,
            minValueRange: null,
            tag: "Make",
          },
          {
            name: "Model",
            type: "string",
            label: "Model",
            desc: "Model",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Model",
            symbols: [],
            comments: null,
            value: "New Model sds",
            maxValueRange: null,
            minValueRange: null,
            tag: "Model",
          },
          {
            name: "Unique_ID",
            type: "string",
            label: "Unique ID",
            desc: "Unique ID",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Unique ID",
            symbols: [],
            comments: null,
            value: "new-cdemand7-device-sds385",
            maxValueRange: null,
            minValueRange: null,
            tag: "Unique_ID",
          },
        ],
      },
      {
        deviceId: 87,
        deviceName: "CDEMAND8",
        desc: null,
        deviceNum: null,
        firmwareVersion: null,
        serialNo: null,
        uniqueIdentifier: "new-cdemand8-device-sds385",
        buildNo: null,
        siteId: 2,
        deviceStatusId: null,
        deviceGroupId: 9,
        gridStatus: null,
        make: null,
        deviceType: {
          deviceTypeId: null,
          deviceTypeName: "CDEMAND-R1",
          deviceGroupName: "CDEMAND",
          deviceGroupDescription: "CDEMAND",
        },
        deviceModel: null,
        points: [
          {
            name: "Make",
            type: "string",
            label: "Make",
            desc: "Make",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Make",
            symbols: [],
            comments: null,
            value: "1232dfdf",
            maxValueRange: null,
            minValueRange: null,
            tag: "Make",
          },
          {
            name: "Model",
            type: "string",
            label: "Model",
            desc: "Model",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Model",
            symbols: [],
            comments: null,
            value: "New Model sds",
            maxValueRange: null,
            minValueRange: null,
            tag: "Model",
          },
          {
            name: "Serial_Num",
            type: "string",
            label: "Serial #",
            desc: "Serial #",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Serial #",
            symbols: [],
            comments: null,
            value: "1234567890",
            maxValueRange: null,
            minValueRange: null,
            tag: "Serial_Num",
          },
          {
            name: "Unique_ID",
            type: "string",
            label: "Unique ID",
            desc: "Unique ID",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Unique ID",
            symbols: [],
            comments: null,
            value: "new-cdemand8-device-sds385",
            maxValueRange: null,
            minValueRange: null,
            tag: "Unique_ID",
          },
        ],
      },
      {
        deviceId: 88,
        deviceName: "CDEMAND9",
        desc: null,
        deviceNum: null,
        firmwareVersion: null,
        serialNo: null,
        uniqueIdentifier: "new-cdemand9-device-sds385",
        buildNo: null,
        siteId: 2,
        deviceStatusId: null,
        deviceGroupId: 9,
        gridStatus: null,
        make: null,
        deviceType: {
          deviceTypeId: null,
          deviceTypeName: "CDEMAND-R1",
          deviceGroupName: "CDEMAND",
          deviceGroupDescription: "CDEMAND",
        },
        deviceModel: null,
        points: [
          {
            name: "Make",
            type: "string",
            label: "Make",
            desc: "Make",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Make",
            symbols: [],
            comments: null,
            value: "1232dfdf",
            maxValueRange: null,
            minValueRange: null,
            tag: "Make",
          },
          {
            name: "Model",
            type: "string",
            label: "Model",
            desc: "Model",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Model",
            symbols: [],
            comments: null,
            value: "New Model sds",
            maxValueRange: null,
            minValueRange: null,
            tag: "Model",
          },
          {
            name: "Unique_ID",
            type: "string",
            label: "Unique ID",
            desc: "Unique ID",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Unique ID",
            symbols: [],
            comments: null,
            value: "new-cdemand9-device-sds385",
            maxValueRange: null,
            minValueRange: null,
            tag: "Unique_ID",
          },
        ],
      },
      {
        deviceId: 89,
        deviceName: "CDEMAND10",
        desc: null,
        deviceNum: null,
        firmwareVersion: null,
        serialNo: null,
        uniqueIdentifier: "new-cdemand10-device-sds385",
        buildNo: null,
        siteId: 2,
        deviceStatusId: null,
        deviceGroupId: 9,
        gridStatus: null,
        make: null,
        deviceType: {
          deviceTypeId: null,
          deviceTypeName: "CDEMAND-R1",
          deviceGroupName: "CDEMAND",
          deviceGroupDescription: "CDEMAND",
        },
        deviceModel: null,
        points: [
          {
            name: "Make",
            type: "string",
            label: "Make",
            desc: "Make",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Make",
            symbols: [],
            comments: null,
            value: "1232dfdf",
            maxValueRange: null,
            minValueRange: null,
            tag: "Make",
          },
          {
            name: "Model",
            type: "string",
            label: "Model",
            desc: "Model",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Model",
            symbols: [],
            comments: null,
            value: "New Model sds",
            maxValueRange: null,
            minValueRange: null,
            tag: "Model",
          },
          {
            name: "Unique_ID",
            type: "string",
            label: "Unique ID",
            desc: "Unique ID",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Unique ID",
            symbols: [],
            comments: null,
            value: "new-cdemand10-device-sds385",
            maxValueRange: null,
            minValueRange: null,
            tag: "Unique_ID",
          },
        ],
      },
      {
        deviceId: 90,
        deviceName: "CDEMAND11",
        desc: null,
        deviceNum: null,
        firmwareVersion: null,
        serialNo: "6666666",
        uniqueIdentifier: "new-cdemand11-device-sds385",
        buildNo: null,
        siteId: 2,
        deviceStatusId: null,
        deviceGroupId: 9,
        gridStatus: null,
        make: null,
        deviceType: {
          deviceTypeId: null,
          deviceTypeName: "CDEMAND-R1",
          deviceGroupName: "CDEMAND",
          deviceGroupDescription: "CDEMAND",
        },
        deviceModel: null,
        points: [
          {
            name: "Make",
            type: "string",
            label: "Make",
            desc: "Make",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Make",
            symbols: [],
            comments: null,
            value: "1232dfdf",
            maxValueRange: null,
            minValueRange: null,
            tag: "Make",
          },
          {
            name: "Model",
            type: "string",
            label: "Model",
            desc: "Model",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Model",
            symbols: [],
            comments: null,
            value: "New Model sds",
            maxValueRange: null,
            minValueRange: null,
            tag: "Model",
          },
          {
            name: "Serial_Num",
            type: "string",
            label: "Serial #",
            desc: "Serial #",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Serial #",
            symbols: [],
            comments: null,
            value: "6666666",
            maxValueRange: null,
            minValueRange: null,
            tag: "Serial_Num",
          },
          {
            name: "Unique_ID",
            type: "string",
            label: "Unique ID",
            desc: "Unique ID",
            sf: "0",
            units: null,
            access: "R",
            mandatory: "1",
            _static: 0,
            size: null,
            detail: "Unique ID",
            symbols: [],
            comments: null,
            value: "new-cdemand11-device-sds385",
            maxValueRange: null,
            minValueRange: null,
            tag: "Unique_ID",
          },
        ],
      },
    ],
  },
];
