module.exports = [
  {
    id: 1,
    name: 'PV Power',
    value: 141.3,
    isEditable: false,
    controlType: 'VDC',
  },
  {
    id: 2,
    name: 'PV Voltage (External)',
    value: 220,
    isEditable: true,
    controlType: 'VDC',
  },
  {
    id: 3,
    name: 'PV Current',
    value: 50,
    isEditable: false,
    controlType: 'A',
  },
  {
    id: 4,
    name: 'PV Voltage (Internal)',
    value: 220,
    isEditable: false,
    controlType: 'VDC',
  },
  {
    id: 5,
    name: 'Bus Voltage (External)',
    value: 240,
    isEditable: false,
    controlType: 'VDC',
  },
  {
    id: 6,
    name: 'Bus Voltage (Internal)',
    value: 240,
    isEditable: false,
    controlType: 'VDC',
  },
  {
    id: 7,
    name: 'Temperature Aproximation',
    value: 15,
    isEditable: false,
    controlType: 'C',
  },
  {
    id: 8,
    name: 'PV Max Voltage SetPoint',
    value: 850,
    isEditable: true,
    controlType: 'VDC',
  },
  {
    id: 9,
    name: 'PV Sleep Voltage SetPoint',
    value: 700,
    isEditable: true,
    controlType: 'VDC',
  },
  {
    id: 10,
    name: 'PV Wake Voltage SetPoint',
    value: 750,
    isEditable: true,
    controlType: 'VDC',
  },
  {
    id: 11,
    name: 'PV Sleep Time',
    value: '20:00:00',
    isEditable: true,
    controlType: '',
  },
  {
    id: 12,
    name: 'Wake-up Time',
    value: '05:00:00',
    isEditable: true,
    controlType: '',
  },
  {
    id: 13,
    name: 'Auto Power-On Enabled',
    value: true,
    isEditable: true,
    controlType: 'boolean',
  },
  {
    id: 14,
    name: 'Discharging',
    value: false,
    isEditable: false,
    controlType: 'boolean',
  },
  {
    id: 15,
    name: 'PV Sleep',
    value: false,
    isEditable: false,
    controlType: 'boolean',
  },
  {
    id: 16,
    name: 'Parameter Saving Enabled/Disabled',
    value: true,
    isEditable: false,
    controlType: 'boolean',
  },
  {
    id: 17,
    name: 'Converter On/Off',
    value: true,
    isEditable: false,
    controlType: 'boolean',
  },
  {
    id: 18,
    name: 'Converter Alarm',
    value: true,
    isEditable: false,
    controlType: 'boolean',
  },
  {
    id: 19,
    name: 'Converter Failure',
    value: true,
    isEditable: true,
    controlType: 'boolean',
  },
];
