module.exports = [
  {
    id: 1,
    name: "PV Setpoint",
    deviceGroupId: 2,
    peakDemand: "830",
    offPeakDemand: "825",
    title1: "825",
    title2: "825",
  },
  {
    id: 2,
    name: "Wind Setpoint",
    deviceGroupId: 2,
    peakDemand: "810",
    offPeakDemand: "825",
    title1: "825",
    title2: "825",
  },
  {
    id: 3,
    name: "Grid-tied Inverter (Maximum)",
    deviceGroupId: 2,
    peakDemand: "750",
    offPeakDemand: "825",
    title1: "825",
    title2: "825",
  },
  {
    id: 4,
    name: "Microturbine Inverter Setpoint",
    deviceGroupId: 2,
    peakDemand: "790",
    offPeakDemand: "825",
    title1: "825",
    title2: "825",
  },
  {
    id: 5,
    name: "R. Engine Inverter Setpoint",
    deviceGroupId: 2,
    peakDemand: "770",
    offPeakDemand: "825",
    title1: "825",
    title2: "825",
  },
  {
    id: 6,
    name: "Battery Charge (Maximum Charge)",
    deviceGroupId: 2,
    peakDemand: "840",
    offPeakDemand: "825",
    title1: "825",
    title2: "825",
  },
  {
    id: 7,
    name: "Battery Discharge (Maximum Charge)",
    deviceGroupId: 2,
    peakDemand: "720",
    offPeakDemand: "825",
    title1: "825",
    title2: "825",
  },
  {
    id: 8,
    name: "R. Engine Inverter (Minimum Voltage)",
    deviceGroupId: 2,
    peakDemand: "720",
    offPeakDemand: "825",
    title1: "825",
    title2: "825",
  },

  {
    id: 9,
    name: "Microturbine Inverter (Minimum Voltage)",
    deviceGroupId: 2,
    peakDemand: "720",
    offPeakDemand: "825",
    title1: "825",
    title2: "825",
  },
  {
    id: 10,
    name: "Grid-tied Inverter (Minimum Voltage)",
    deviceGroupId: 2,
    peakDemand: "830",
    offPeakDemand: "825",
    title1: "825",
    title2: "825",
  },
  {
    id: 11,
    name: "Non-Grid Connected Inverter (Minimum Voltage)",
    deviceGroupId: 2,
    peakDemand: "830",
    offPeakDemand: "825",
    title1: "825",
    title2: "825",
  },
];
