// sitesList.js
module.exports = [
  {
    siteId: 1,
    externalId: "25251sdsdSD111",
    name: "Bad River",
    plcId: "BADRIVER",
    icianName: "Elvin Jones",
    latitude: "9.1231231231",
    longitude: "34.232323232",
    companyName: "Atlantida Inc.",
    points: [
      {
        name: "SiteStatus",
        type: "uint16",
        label: "Site Status",
        description: "Site Status",
        access: "R",
        mandatory: "true",
        symbols: [
          {
            name: "MAINTENANCE",
            value: "1",
            label: "Site Status",
            description: "Site Status",
            active: false,
          },
          {
            name: "FAULTED",
            value: "2",
            label: "Site Status",
            description: "Site Status",
            active: false,
          },
          {
            name: "ALARM",
            value: "3",
            label: "Site Status",
            description: "Site Status",
            active: false,
          },
          {
            name: "WARNING",
            value: "4",
            label: "Site Status",
            description: "Site Status",
            active: false,
          },
          {
            name: "OK",
            value: "5",
            label: "Site Status",
            description: "Site Status",
            active: false,
          },
        ],
        value: "5",
        active: false,
      },
      {
        name: "IslandMode",
        type: "uint16",
        label: "Island Mode",
        description: "Island Mode",
        access: "R",
        mandatory: "true",
        symbols: [
          {
            name: "Island Mode",
            value: "1",
            label: "Island Mode",
            description: "Communication Status",
            active: false,
          },
          {
            name: "Island Mode",
            value: "2",
            label: "Island Mode",
            description: "Communication Status",
            active: false,
          },
        ],
        value: "2",
        active: false,
      },
      {
        name: "CommStatus",
        type: "uint16",
        label: "Communications Status",
        description: "Communications Status",
        access: "R",
        mandatory: "true",
        symbols: [
          {
            name: "Landline",
            value: "1",
            label: "Communication Status",
            description: "Communication Status",
            active: false,
          },
          {
            name: "Cellular",
            value: "2",
            label: "Communication Status",
            description: "Communication Status",
            active: false,
          },
          {
            name: "Disconnected",
            value: "3",
            label: "Communication Status",
            description: "Communication Status",
            active: false,
          },
        ],
        value: "3",
        active: false,
      },
    ],
  },
  {
    siteId: 2,
    externalId: "78251xxffSD666",
    name: "Lab 3",
    plcId: "LAB3",
    icianName: "Bruce Dickinson",
    latitude: "12.1234455231",
    longitude: "6.778899232",
    companyName: "Umbrella Inc.",
    points: [
      {
        name: "SiteStatus",
        type: "uint16",
        label: "Site Status",
        description: "Site Status",
        access: "R",
        mandatory: "true",
        symbols: [
          {
            name: "MAINTENANCE",
            value: "1",
            label: "Site Status",
            description: "Site Status",
            active: false,
          },
          {
            name: "FAULTED",
            value: "2",
            label: "Site Status",
            description: "Site Status",
            active: false,
          },
          {
            name: "ALARM",
            value: "3",
            label: "Site Status",
            description: "Site Status",
            active: false,
          },
          {
            name: "WARNING",
            value: "4",
            label: "Site Status",
            description: "Site Status",
            active: false,
          },
          {
            name: "OK",
            value: "5",
            label: "Site Status",
            description: "Site Status",
            active: false,
          },
        ],
        value: "3",
        active: false,
      },
      {
        name: "IslandMode",
        type: "uint16",
        label: "Island Mode",
        description: "Island Mode",
        access: "R",
        mandatory: "true",
        symbols: [
          {
            name: "Island Mode",
            value: "1",
            label: "Island Mode",
            description: "Communication Status",
            active: false,
          },
          {
            name: "Island Mode",
            value: "2",
            label: "Island Mode",
            description: "Communication Status",
            active: false,
          },
          {
            name: "Island Mode",
            value: "3",
            label: "Island Mode",
            description: "Communication Status",
            active: false,
          },
        ],
        value: "3",
        active: false,
      },
      {
        name: "CommStatus",
        type: "uint16",
        label: "Communications Status",
        description: "Communications Status",
        access: "R",
        mandatory: "true",
        symbols: [
          {
            name: "Landline",
            value: "1",
            label: "Communication Status",
            description: "Communication Status",
            active: false,
          },
          {
            name: "Cellular",
            value: "2",
            label: "Communication Status",
            description: "Communication Status",
            active: false,
          },
          {
            name: "Disconnected",
            value: "3",
            label: "Communication Status",
            description: "Communication Status",
            active: false,
          },
        ],
        value: "3",
        active: false,
      },
    ],
  },
  {
    siteId: 3,
    externalId: "25901ddrrFX999",
    name: "Development",
    plcId: "DEV",
    icianName: "Ronnie James Dio",
    latitude: "155.1236466666",
    longitude: "99.582469232",
    companyName: "Microsoft Inc.",
    points: [
      {
        name: "SiteStatus",
        type: "uint16",
        label: "Site Status",
        description: "Site Status",
        access: "R",
        mandatory: "true",
        symbols: [
          {
            name: "MAINTENANCE",
            value: "1",
            label: "Site Status",
            description: "Site Status",
            active: false,
          },
          {
            name: "FAULTED",
            value: "2",
            label: "Site Status",
            description: "Site Status",
            active: false,
          },
          {
            name: "ALARM",
            value: "3",
            label: "Site Status",
            description: "Site Status",
            active: false,
          },
          {
            name: "WARNING",
            value: "4",
            label: "Site Status",
            description: "Site Status",
            active: false,
          },
          {
            name: "OK",
            value: "5",
            label: "Site Status",
            description: "Site Status",
            active: false,
          },
        ],
        value: "2",
        active: false,
      },
      {
        name: "IslandMode",
        type: "uint16",
        label: "Island Mode",
        description: "Island Mode",
        access: "R",
        mandatory: "true",
        symbols: [
          {
            name: "Island Mode",
            value: "1",
            label: "Island Mode",
            description: "Communication Status",
            active: false,
          },
        ],
        value: "1",
        active: false,
      },
      {
        name: "CommStatus",
        type: "uint16",
        label: "Communications Status",
        description: "Communications Status",
        access: "R",
        mandatory: "true",
        symbols: [
          {
            name: "Landline",
            value: "1",
            label: "Communication Status",
            description: "Communication Status",
            active: false,
          },
          {
            name: "Cellular",
            value: "2",
            label: "Communication Status",
            description: "Communication Status",
            active: false,
          },
          {
            name: "Disconnected",
            value: "3",
            label: "Communication Status",
            description: "Communication Status",
            active: false,
          },
        ],
        value: "2",
        active: false,
      },
    ],
  },
  {
    siteId: 4,
    externalId: "25901ddrrFX999",
    name: "Quality",
    plcId: "QA",
    icianName: "Tobias Sammeth",
    latitude: "55.66654546666",
    longitude: "66.998877442",
    companyName: "Apple Inc.",
    points: [
      {
        name: "SiteStatus",
        type: "uint16",
        label: "Site Status",
        description: "Site Status",
        access: "R",
        mandatory: "true",
        symbols: [
          {
            name: "MAINTENANCE",
            value: "1",
            label: "Site Status",
            description: "Site Status",
            active: false,
          },
          {
            name: "FAULTED",
            value: "2",
            label: "Site Status",
            description: "Site Status",
            active: false,
          },
          {
            name: "ALARM",
            value: "3",
            label: "Site Status",
            description: "Site Status",
            active: false,
          },
          {
            name: "WARNING",
            value: "4",
            label: "Site Status",
            description: "Site Status",
            active: false,
          },
          {
            name: "OK",
            value: "5",
            label: "Site Status",
            description: "Site Status",
            active: false,
          },
        ],
        value: "1",
        active: false,
      },
      {
        name: "IslandMode",
        type: "uint16",
        label: "Island Mode",
        description: "Island Mode",
        access: "R",
        mandatory: "true",
        symbols: [
          {
            name: "Island Mode",
            value: "1",
            label: "Island Mode",
            description: "Communication Status",
            active: false,
          },
          {
            name: "Island Mode",
            value: "2",
            label: "Island Mode",
            description: "Communication Status",
            active: false,
          },
          {
            name: "Island Mode",
            value: "3",
            label: "Island Mode",
            description: "Communication Status",
            active: false,
          },
        ],
        value: "1",
        active: false,
      },
      {
        name: "CommStatus",
        type: "uint16",
        label: "Communications Status",
        description: "Communications Status",
        access: "R",
        mandatory: "true",
        symbols: [
          {
            name: "Landline",
            value: "1",
            label: "Communication Status",
            description: "Communication Status",
            active: false,
          },
          {
            name: "Cellular",
            value: "2",
            label: "Communication Status",
            description: "Communication Status",
            active: false,
          },
          {
            name: "Disconnected",
            value: "3",
            label: "Communication Status",
            description: "Communication Status",
            active: false,
          },
        ],
        value: "1",
        active: false,
      },
    ],
  },
];
